kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: Show flake info
  image: nixpkgs/nix-flakes
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake info
  - nix --experimental-features "nix-command flakes" flake list-inputs
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Run flake checks
  image: nixpkgs/nix-flakes
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Build flake output
  image: nixpkgs/nix-flakes
  commands:
  - nix build
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

- name: Run generator
  image: nixpkgs/nix-flakes
  commands:
  - nix run ".#" -- harmonograph
  environment:
    NIX_PATH: nixpkgs=channel:nixos-unstable

